# Generated by Django 4.0.2 on 2022-05-31 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_language_options_alter_genre_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['status', 'due_back']},
        ),
    ]
